
const $=id=>document.getElementById(id);let token='',records=[],patients=[],jobs=[],readiness={},config={};
const names={review:'Needs review',fallback:'Staff review required',pending:'Awaiting confirmation',confirmed:'Confirmed',scheduled:'Reminders scheduled',in_progress:'Call in progress',completed:'Completed',cancelled_consent:'Consent withdrawn'};
const dispatchNames={not_sent:'Not dialled',submitting:'Dialling now',submitted:'Awaiting outcome',unknown:'Outcome unknown'};
const blockerHelp={'Live calling disabled':'set CALLE_ENABLE_LIVE_CALLS=true','No call budget configured':'set CALLE_CALL_BUDGET to the maximum number of calls this deployment may place','No allowed phone numbers configured':'list every number you may dial in CALLE_ALLOWED_PHONES, comma separated, E.164','Public HTTPS base URL missing or invalid':'set MEDAI_PUBLIC_BASE_URL to the https origin the provider can reach','No conversationally verified locales configured':'list locales you have tested end to end in CALLE_VERIFIED_LOCALES','API key missing':'set CALLE_API_KEY'};
function node(tag,text,parent,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;if(parent)parent.append(n);return n;}
function say(text,error=false){const box=$('detail').open?$('detailnotice'):$('notice');box.textContent=text;box.hidden=false;box.className='notice'+(error?' error':'');}
async function api(path,method='GET',body){const requestToken=token;const r=await fetch('/local/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw Error('The server could not complete the request.');}if(token!==requestToken)throw Error('Workspace session changed.');if(!r.ok){const e=Error(Array.isArray(d.detail)?d.detail.map(x=>typeof x==='string'?x:(x.loc?.slice(1).join(' ')||'Field')+': '+x.msg).join('\n'):d.detail||'Request failed');e.status=r.status;throw e;}return d;}
function show(v){['queue','intake','jobs','settings'].forEach(x=>$(x+'view').hidden=x!==v);$('title').textContent={queue:'Prescriptions',intake:'New prescription',jobs:'Reminders',settings:'Settings'}[v];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));}
async function load(){[records,patients,jobs,readiness,config]=await Promise.all([api('confirmations'),api('patients'),api('jobs'),api('readiness'),api('config')]);$('reviewcount').textContent=records.filter(d=>['review','fallback'].includes(d.status)).length;$('pendingcount').textContent=records.filter(d=>d.status==='pending').length;$('approvedcount').textContent=records.filter(d=>['confirmed','scheduled'].includes(d.status)).length;renderReadiness();const selected=$('existing').value;$('existing').replaceChildren(new Option('Add a new patient',''));patients.forEach(p=>$('existing').add(new Option(p.name,p.patient_id)));$('existing').value=selected;render();renderJobs();renderSettings();await loadScans();}
function renderWorker(){const w=config.automation||{},live=w.running&&w.mode==='live';
const label=live?'Dialling reminders automatically':w.running?'Running, dry-run only':'Worker not running';
['workerstate','jobsworker'].forEach(id=>{$(id).textContent=label;$(id).className='pill '+(live?'ready':'paused');});
$('workerdetail').textContent=w.seen_at?'Last reported in '+w.age_seconds+'s ago ('+new Date(w.seen_at).toLocaleString()+'), mode: '+(w.mode||'unknown')+'.'+(w.running&&w.mode!=='live'?' In dry-run it lists due reminders without dialling any.':''):'This worker has never reported in on this database. Due reminders stay unplaced until you start it, or dial them by hand from the Reminders view.';}
function renderSettings(){const c=config.calling||{},st=config.storage||{},au=config.auth||{};
const limit=c.working_limit||0,reserved=c.reserved||0,left=Math.max(0,limit-reserved);
$('budgetlimit').value=limit;$('budgetceiling').value=c.ceiling||0;$('budgetreserved').value=reserved;$('budgetleft').value=left;
$('budgetstate').textContent=left>0?left+' call(s) available':'No calls available';
$('budgetstate').className='pill '+(left>0?'ready':'paused');
renderWorker();
const facts=$('configfacts');facts.replaceChildren();
[['Live calling',c.enabled?'Enabled':'Disabled'],
 ['Allowed numbers',(c.allowed_phone_count||0)+' number(s) on the allowlist'],
 ['Verified locales',(c.verified_locales||[]).join(', ')||'none configured'],
 ['Provider host',c.provider_host||'unset'],
 ['Webhook callback host',c.callback_host||'unset \u2014 outcomes must be read back by hand'],
 ['Workspace tenant',st.tenant||'\u2014'],
 ['Database file',st.database||'\u2014'],
 ['Reminders stored',(st.scheduled_jobs||0)+' saved, '+(st.due_jobs||0)+' due now'],
 ['Staff authentication',au.named_staff_keys?'Named staff keys':'Single shared staff token'],
 ['Legacy demo endpoints',au.legacy_demo_enabled?'Enabled':'Disabled']]
.forEach(([k,v])=>{const r=node('div','',facts,'summary');node('h3',k,r);node('p',v,r,'muted');});}
function budgetLeft(){return (readiness.local_budget||0)-(readiness.reserved_calls||0);}
function callsAvailable(){return !!readiness.configured_for_live&&budgetLeft()>0;}
function renderReadiness(){const ok=!!readiness.configured_for_live,blockers=readiness.blockers||[],used=readiness.reserved_calls||0,limit=readiness.local_budget||0,spent=ok&&budgetLeft()<=0;
$('live').textContent=spent?'Call budget spent':ok?'Calling configured':'Calling paused';$('live').className='pill '+(callsAvailable()?'ready':'paused');
$('readystate').textContent=spent?'Budget spent':ok?'Ready to place calls':'Not ready';$('readystate').className='pill '+(callsAvailable()?'ready':'paused');
$('callsused').textContent=used+' / '+limit;
$('budget').textContent=ok?'Every dispatch reserves one call from the local budget before the provider is contacted. A reserved call is never released, even if the provider never answers.':'Set the configuration below, then restart the server and unlock the workspace again.';
$('blockers').replaceChildren();
blockers.forEach(b=>node('li',blockerHelp[b]?b+' \u2014 '+blockerHelp[b]:b,$('blockers')));
if(spent)node('li','Local call budget spent: '+used+' of '+limit+' reserved. Raise CALLE_CALL_BUDGET and restart the server to allow another call. Reserved calls are never released, so a raised budget does not undo a call already placed.',$('blockers'));
else if(!blockers.length)node('li','No configuration blockers, '+budgetLeft()+' call(s) left in the local budget. Calls are still placed one at a time, by hand.',$('blockers'));}
function render(){const parent=$('records');parent.replaceChildren();const q=$('search').value.toLowerCase(),f=$('filter').value;const docs=records.filter(d=>d.patient_name.toLowerCase().includes(q)&&(f==='all'||(f==='review'?['review','fallback'].includes(d.status):f==='confirmed'?['confirmed','scheduled'].includes(d.status):d.status===f)));if(!docs.length){const e=node('div','',parent,'empty');node('h2',records.length?'No matching prescriptions':'Your first prescription starts here',e);node('p',records.length?'Try a different name or status.':'Add a patient and their prescribed medicines to begin confirmation and review.',e);if(!records.length){const b=node('button','Add prescription',e,'primary');b.onclick=()=>show('intake');}return;}for(const d of docs){const row=node('div','',parent,'row'),a=node('div','',row);node('h3',d.patient_name,a);node('p',d.source_id,a,'muted');const meta=node('div','',row,'metadata');node('span',names[d.status]||d.status,meta,'pill '+d.status);dispatchPill(meta,d);node('p',d.medications.length+' medicines',meta,'muted');const b=node('button',['review','fallback'].includes(d.status)?'Review prescription':'View prescription',row);b.onclick=()=>openDetail(d);}}
function field(parent,label,value='',required=true){const wrap=node('label',label,parent,'field'),input=node('input','',wrap);input.value=value;input.required=required;return input;}
function editor(parent,med={}){const box=node('div','',parent,'med'),top=node('div','',box,'sectionhead');node('h3','Medicine',top);const remove=node('button','Remove',top);remove.type='button';remove.onclick=()=>box.remove();const grid=node('div','',box,'grid'),fields={};for(const [key,label]of [['name','Medicine name'],['dosage','Dose'],['quantity','Quantity'],['schedule','Timing (comma separated)'],['duration','Duration'],['instructions','Instructions']])fields[key]=field(grid,label,key==='schedule'?(med[key]||[]).join(', '):med[key]||'',key!=='instructions');box.read=()=>{const m={};for(const[k,input]of Object.entries(fields)){if(!input.reportValidity())throw Error('Complete each required medicine field.');m[k]=k==='schedule'?input.value.split(',').map(s=>s.trim()).filter(Boolean):input.value.trim();}return m;};}
function readMeds(parent){const meds=[...parent.children].map(b=>b.read());if(!meds.length)throw Error('Add at least one medicine.');return meds;}
function summarize(parent,meds){meds.forEach(m=>{const row=node('div','',parent,'summary');node('h3',m.name+' · '+m.dosage,row);node('p',[m.quantity,m.schedule.join(', '),m.duration,m.instructions].filter(Boolean).join(' · '),row,'muted');});}
function dispatchPill(parent,d){if(d.dispatch_state&&d.dispatch_state!=='not_sent')node('span',dispatchNames[d.dispatch_state]||d.dispatch_state,parent,'pill dispatch '+d.dispatch_state);}
function callState(body,d){
if(d.dispatch_state==='unknown')node('p','The provider never confirmed this submission, so the call may still have been placed. The reserved call is kept and this dashboard will not redial. Reconcile with the provider before any retry.',body,'muted');
const f=d.provider_failure||{};if(f.failure_code||f.failure_message)node('p','Provider reported: '+[f.failure_code,f.failure_message].filter(Boolean).join(' \u00b7 '),body,'muted');
if(d.dispatch_state!=='submitted')return;
node('p','The provider accepted this call. That is not proof the phone connected \u2014 read the outcome back from the provider.',body,'muted');
const b=node('button','Check outcome with provider',body);
b.onclick=async()=>{b.disabled=true;try{const r=await api('confirmations/'+d.call_id+'/reconcile','POST',{});
if(r.status==='active'){const never=r.dial_attempts===0,since=r.submitted_at?' since '+new Date(r.submitted_at).toLocaleString():'';say(never?'The provider accepted this call at '+(r.submitted_at?new Date(r.submitted_at).toLocaleString():'submission')+' but has not attempted to dial even once (status: '+r.call_status+'). A call that stays queued with no dial attempt is a provider-side problem, not a fault in this workspace \u2014 check that the account has calling credit and that outbound calling is enabled for this number\u2019s region.':'The provider still reports this call as '+r.call_status+' after '+r.dial_attempts+' dial attempt(s)'+since+'. Check again once it ends.',never);b.disabled=false;return;}
$('detail').close();await load();say('Call '+r.call_status+'. This prescription is now: '+(names[r.disposition]||r.disposition)+'.');}
catch(err){say(err.message,true);b.disabled=false;}};}
function openDetail(d){$('detailtitle').textContent=d.patient_name;$('detailnotice').hidden=true;const body=$('detailbody');body.replaceChildren();node('span',names[d.status]||d.status,body,'pill '+d.status);dispatchPill(body,d);node('p','Prescription: '+d.source_id,body,'muted');callState(body,d);for(const m of d.structured_result?.medications||[]){if(m.correction_text||m.status==='unsure'){const q=node('div','',body,'quote');node('strong',m.name_as_read,q);node('p',m.correction_text||'Patient was unsure.',q);}}if(d.fallback_reason)node('p',{unsupported_language:'This language is not yet verified for calls. Review the prescription manually.',medication_limit:'This prescription needs staff review because of its length.',consent_withdrawn:'The patient withdrew consent.'}[d.fallback_reason]||d.fallback_reason,body,'muted');
if(['review','fallback'].includes(d.status)){node('h3','Verify against the original prescription',body);node('p','Corrections are not applied automatically.',body,'muted');const form=node('form','',body),meds=node('div','',form);d.medications.forEach(m=>editor(meds,m));const add=node('button','+ Add medicine',form);add.type='button';add.onclick=()=>editor(meds);const reason=field(form,'Verification notes');const approve=node('button','Approve reviewed prescription',form,'primary');approve.style.marginTop='16px';form.onsubmit=async e=>{e.preventDefault();approve.disabled=true;try{await api('confirmations/'+d.call_id+'/approve','POST',{medications:readMeds(meds),reason:reason.value,version:d.version});$('detail').close();await load();say('Prescription approved. You can now schedule reminders.');}catch(err){say(err.message,true);}finally{approve.disabled=false;}};}
else{summarize(body,d.approved_medications||d.medications);if(d.status==='pending'&&d.dispatch_state==='not_sent'){const preview=node('button','Preview confirmation call',body);preview.onclick=async()=>{preview.disabled=true;try{const p=await api('confirmations/'+d.call_id+'/preview'),area=node('div','',body,'callprep');node('h3','Call preview',area);node('pre',p.task||'No call script: this prescription needs staff review.',area);const blocked=p.live_blockers||[];blocked.forEach(x=>node('p',blockerHelp[x]?x+' \u2014 '+blockerHelp[x]:x,area,'muted'));const call=node('button','Place one live call',area,'primary');call.disabled=blocked.length>0||!p.task||!callsAvailable();if(!blocked.length&&p.task&&!callsAvailable())node('p','The local call budget is spent ('+(readiness.reserved_calls||0)+' of '+(readiness.local_budget||0)+' reserved). Raise CALLE_CALL_BUDGET and restart the server before placing another call.',area,'muted');if(!p.task)node('p','This prescription is too long to read back in one call. Confirm it with the patient another way.',area,'muted');if(blocked.length)node('p','Fix the configuration above, restart the server, then unlock the workspace again.',area,'muted');call.onclick=async()=>{if(!confirm('Place one real call to '+d.phone_number+'?\n\nThis dials a real phone and permanently spends one call from the local budget.'))return;call.disabled=true;try{await api('confirmations/'+d.call_id+'/dispatch','POST',{});$('detail').close();await load();say('Call submitted to the provider. Open this prescription again and check the outcome once the call ends.');}catch(err){say(err.message,true);if(err.status!==502)call.disabled=false;}};}catch(err){say(err.message,true);preview.disabled=false;}};}
if(['confirmed','scheduled'].includes(d.status)){const form=node('form','',body);node('h3','Schedule a reminder',form);const wrap=node('label','Medicine',form,'field'),select=node('select','',wrap);(d.approved_medications||d.medications).forEach(m=>select.add(new Option(m.name,m.name)));const due=field(form,'Reminder time · '+Intl.DateTimeFormat().resolvedOptions().timeZone);due.type='datetime-local';const save=node('button','Save reminder',form,'primary');save.style.marginTop='16px';form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('confirmations/'+d.call_id+'/schedule','POST',{due_at:[new Date(due.value).toISOString()],medication_names:[select.value],version:d.version});$('detail').close();await load();say('Reminder saved.');}catch(err){say(err.message,true);}finally{save.disabled=false;}};}}$('detail').showModal();}
function jobAction(row,j){if(j.status!=='pending'||j.dispatch_state!=='not_sent'){node('span','',row);return;}
const due=new Date(j.due_at)<=new Date(),ok=callsAvailable();
const b=node('button',due?'Place reminder call':'Not due yet',row);b.disabled=!due||!ok;
if(due&&!ok)b.title=readiness.configured_for_live?'The local call budget is spent. Raise CALLE_CALL_BUDGET and restart the server.':'Calling is not configured. See Call readiness on the Prescriptions view.';
b.onclick=async()=>{if(!confirm('Place one real reminder call to '+(j.phone_number||'the recipient')+' now?\n\nThis dials a real phone and permanently spends one call from the local budget.'))return;b.disabled=true;
try{await api('jobs/'+j.job_id+'/dispatch','POST',{});await load();say('Reminder call submitted to the provider. An accepted request is not proof the phone connected.');}
catch(err){say(err.message,true);if(err.status!==502)b.disabled=false;}};}
function renderJobs(){const parent=$('jobs');parent.replaceChildren();if(!jobs.length){const e=node('div','',parent,'empty');node('h2','No reminders scheduled',e);
node('p','A reminder is created from an approved prescription: open one that is confirmed, pick a medicine and a time. Reminders are dialled automatically by the worker once they fall due, or by hand from this view.',e);
const b=node('button','Go to prescriptions',e,'primary');b.onclick=()=>show('queue');return;}jobs.forEach(j=>{const row=node('div','',parent,'row'),a=node('div','',row);node('h3',patients.find(p=>p.patient_id===j.patient_id)?.name||j.patient_id,a);node('p',(j.kind==='escalation'?'Caregiver escalation \u00b7 ':'')+(j.medication?.name||'Reminder'),a,'muted');const meta=node('div','',row,'metadata');node('p',new Date(j.due_at).toLocaleString(),meta);node('span',names[j.status]||j.status,meta,'pill '+j.status);dispatchPill(meta,j);jobAction(row,j);});}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>token?show(b.dataset.view):say('Unlock the workspace first.'));$('new').onclick=()=>show('intake');$('cancel').onclick=()=>show('queue');$('close').onclick=()=>$('detail').close();$('addmed').onclick=()=>editor($('medications'));$('search').oninput=render;$('filter').onchange=render;
$('loginform').onsubmit=async e=>{e.preventDefault();token=$('token').value.trim();try{await load();$('token').value='';$('login').hidden=true;$('workspace').hidden=false;$('refresh').hidden=false;$('lock').hidden=false;$('notice').hidden=true;}catch(err){token='';say(err.message,true);}};$('refresh').onclick=async()=>{try{await load();say('Workspace updated.');}catch(err){say(err.message,true);}};$('budgetform').onsubmit=async e=>{e.preventDefault();$('savebudget').disabled=true;
try{const r=await api('config/budget','POST',{limit:Number($('budgetlimit').value)});await load();
say('Working call limit set to '+r.working_limit+'. '+Math.max(0,r.working_limit-r.reserved)+' call(s) available now.');}
catch(err){say(err.message,true);}finally{$('savebudget').disabled=false;}};
$('lock').onclick=()=>{token='';records=[];patients=[];jobs=[];readiness={};config={};$('configfacts').replaceChildren();$('workerdetail').textContent='';$('blockers').replaceChildren();$('detailnotice').hidden=true;$('live').textContent='Calling paused';$('live').className='pill paused';$('readystate').textContent='Not ready';$('readystate').className='pill paused';$('callsused').textContent='0 / 0';$('budget').textContent='';$('workspace').hidden=true;$('login').hidden=false;$('refresh').hidden=true;$('lock').hidden=true;$('detail').close();$('detailbody').replaceChildren();$('records').replaceChildren();$('jobs').replaceChildren();$('intakeform').reset();$('existing').replaceChildren(new Option('Add a new patient',''));$('savedscans').replaceChildren(new Option('Choose a saved scan',''));$('medications').replaceChildren();editor($('medications'));$('notice').hidden=true;};
$('existing').onchange=()=>{const p=patients.find(p=>p.patient_id===$('existing').value);for(const[id,key]of [['name','name'],['phone','phone'],['language','language'],['region','region'],['evidence','consent_evidence']])$(id).value=p?.[key]||(['language','region'].includes(id)?(id==='language'?'en-IN':'IN'):'');$('consent').checked=Boolean(p?.consent&&!p?.consent_withdrawn_at);};
$('intakeform').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const meds=readMeds($('medications'));const id=$('existing').value||crypto.randomUUID(),original=patients.find(p=>p.patient_id===id)||{};await api('patients','PUT',{patient_id:id,name:$('name').value.trim(),phone:$('phone').value.trim(),language:$('language').value,region:$('region').value,consent:$('consent').checked,consent_evidence:$('evidence').value.trim(),caregiver_name:original.caregiver_name,caregiver_phone:original.caregiver_phone,caregiver_language:original.caregiver_language,caregiver_region:original.caregiver_region});await api('intakes','POST',{patient_id:id,source_id:$('source').value.trim(),medications:meds,ocr_reviewed:!!ocrScan&&$('ocrchecked').checked});$('intakeform').reset();$('medications').replaceChildren();editor($('medications'));await load();show('queue');say('Prescription saved. No call has been placed.');}catch(err){say(err.message,true);}finally{$('save').disabled=false;}};editor($('medications'));

let ocrScan=null,ocrDrafts=[],ocrGeneration=0;
function clearOCR(){ocrGeneration++;ocrScan=null;ocrDrafts=[];$('ocrtext').textContent='';$('ocrresult').hidden=true;$('ocrchecked').checked=false;$('ocrchecked').required=false;$('source').readOnly=false;}
$('ocrfile').onchange=()=>{clearOCR();};
$('intakeform').addEventListener('reset',clearOCR);
$('extractocr').onclick=async()=>{const f=$('ocrfile').files[0];if(!f){say('Choose a prescription file first.',true);return;}if(f.size>10*1024*1024){say('Maximum upload size is 10 MB.',true);return;}clearOCR();const requestGeneration=ocrGeneration,requestToken=token;$('extractocr').disabled=true;$('save').disabled=true;say('Reading the prescription locally…');try{const r=await fetch('/local/ocr/extract',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/octet-stream'},body:f});const d=await r.json();if(requestToken!==token||requestGeneration!==ocrGeneration)return;if(!r.ok)throw Error(d.detail||'OCR failed');displayScan(d);await loadScans();say('Scan saved. Use suggested fields, then verify against the original and fill missing details.');}catch(e){say(e.message,true);}finally{$('extractocr').disabled=false;$('save').disabled=false;}};

async function loadScans(){const scans=await api('ocr');$('savedscans').replaceChildren(new Option('Choose a saved scan',''));scans.forEach(d=>$('savedscans').add(new Option((d.created_at?new Date(d.created_at).toLocaleString():d.scan_id)+' · '+d.pages+' page(s)',d.scan_id)));}
function displayScan(d){ocrScan=d.scan_id;ocrDrafts=d.draft_medications||[];$('source').value=d.scan_id;$('source').readOnly=true;$('ocrtext').textContent=d.text;$('ocrresult').hidden=false;$('ocrchecked').checked=false;$('ocrchecked').required=true;$('usedraft').disabled=!ocrDrafts.length;if(ocrDrafts.length){$('medications').replaceChildren();ocrDrafts.forEach(m=>editor($('medications'),m));}}
$('openscan').onclick=async()=>{try{if(!$('savedscans').value)throw Error('Choose a saved scan first.');displayScan(await api('ocr/'+encodeURIComponent($('savedscans').value)));say('Saved scan loaded. Review the source before saving.');}catch(e){say(e.message,true);}};
$('usedraft').onclick=()=>{if(!ocrDrafts.length)return;if(!confirm('Replace the current medicine fields with unverified suggestions from this scan?'))return;$('medications').replaceChildren();ocrDrafts.forEach(m=>editor($('medications'),m));$('ocrchecked').checked=false;say('Suggestions loaded. Blank fields were not present in the source. Verify all values before saving.');};
$('downloadsource').onclick=async()=>{try{const r=await fetch('/local/ocr/'+encodeURIComponent(ocrScan)+'/source',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Original file is unavailable for this scan.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='prescription-source';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){say(e.message,true);}};
