
const $=id=>document.getElementById(id);let token='',records=[],patients=[],jobs=[],readiness={};
const names={review:'Needs review',fallback:'Staff review required',pending:'Awaiting confirmation',confirmed:'Confirmed',scheduled:'Reminders scheduled',in_progress:'Call in progress',completed:'Completed',cancelled_consent:'Consent withdrawn'};
function node(tag,text,parent,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;if(parent)parent.append(n);return n;}
function say(text,error=false){$('notice').textContent=text;$('notice').hidden=false;$('notice').className='notice'+(error?' error':'');}
async function api(path,method='GET',body){const requestToken=token;const r=await fetch('/local/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw Error('The server could not complete the request.');}if(token!==requestToken)throw Error('Workspace session changed.');if(!r.ok){throw Error(Array.isArray(d.detail)?d.detail.map(x=>typeof x==='string'?x:(x.loc?.slice(1).join(' ')||'Field')+': '+x.msg).join('\n'):d.detail||'Request failed');}return d;}
function show(v){['queue','intake','jobs'].forEach(x=>$(x+'view').hidden=x!==v);$('title').textContent={queue:'Prescriptions',intake:'New prescription',jobs:'Reminders'}[v];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));}
async function load(){[records,patients,jobs,readiness]=await Promise.all([api('confirmations'),api('patients'),api('jobs'),api('readiness')]);$('reviewcount').textContent=records.filter(d=>['review','fallback'].includes(d.status)).length;$('pendingcount').textContent=records.filter(d=>d.status==='pending').length;$('approvedcount').textContent=records.filter(d=>['confirmed','scheduled'].includes(d.status)).length;$('live').textContent=readiness.configured_for_live?'Calling configured':'Calling paused';$('blockers').replaceChildren();(readiness.blockers||[]).forEach(s=>node('li',s,$('blockers')));const selected=$('existing').value;$('existing').replaceChildren(new Option('Add a new patient',''));patients.forEach(p=>$('existing').add(new Option(p.name,p.patient_id)));$('existing').value=selected;render();renderJobs();await loadScans();}
function render(){const parent=$('records');parent.replaceChildren();const q=$('search').value.toLowerCase(),f=$('filter').value;const docs=records.filter(d=>d.patient_name.toLowerCase().includes(q)&&(f==='all'||(f==='review'?['review','fallback'].includes(d.status):f==='confirmed'?['confirmed','scheduled'].includes(d.status):d.status===f)));if(!docs.length){const e=node('div','',parent,'empty');node('h2',records.length?'No matching prescriptions':'Your first prescription starts here',e);node('p',records.length?'Try a different name or status.':'Add a patient and their prescribed medicines to begin confirmation and review.',e);if(!records.length){const b=node('button','Add prescription',e,'primary');b.onclick=()=>show('intake');}return;}for(const d of docs){const row=node('div','',parent,'row'),a=node('div','',row);node('h3',d.patient_name,a);node('p',d.source_id,a,'muted');const meta=node('div','',row,'metadata');node('span',names[d.status]||d.status,meta,'pill '+d.status);node('p',d.medications.length+' medicines',meta,'muted');const b=node('button',['review','fallback'].includes(d.status)?'Review prescription':'View prescription',row);b.onclick=()=>openDetail(d);}}
function field(parent,label,value='',required=true){const wrap=node('label',label,parent,'field'),input=node('input','',wrap);input.value=value;input.required=required;return input;}
function editor(parent,med={}){const box=node('div','',parent,'med'),top=node('div','',box,'sectionhead');node('h3','Medicine',top);const remove=node('button','Remove',top);remove.type='button';remove.onclick=()=>box.remove();const grid=node('div','',box,'grid'),fields={};for(const [key,label]of [['name','Medicine name'],['dosage','Dose'],['quantity','Quantity'],['schedule','Timing (comma separated)'],['duration','Duration'],['instructions','Instructions']])fields[key]=field(grid,label,key==='schedule'?(med[key]||[]).join(', '):med[key]||'',key!=='instructions');box.read=()=>{const m={};for(const[k,input]of Object.entries(fields)){if(!input.reportValidity())throw Error('Complete each required medicine field.');m[k]=k==='schedule'?input.value.split(',').map(s=>s.trim()).filter(Boolean):input.value.trim();}return m;};}
function readMeds(parent){const meds=[...parent.children].map(b=>b.read());if(!meds.length)throw Error('Add at least one medicine.');return meds;}
function summarize(parent,meds){meds.forEach(m=>{const row=node('div','',parent,'summary');node('h3',m.name+' · '+m.dosage,row);node('p',[m.quantity,m.schedule.join(', '),m.duration,m.instructions].filter(Boolean).join(' · '),row,'muted');});}
function openDetail(d){$('detailtitle').textContent=d.patient_name;const body=$('detailbody');body.replaceChildren();node('span',names[d.status]||d.status,body,'pill '+d.status);node('p','Prescription: '+d.source_id,body,'muted');for(const m of d.structured_result?.medications||[]){if(m.correction_text||m.status==='unsure'){const q=node('div','',body,'quote');node('strong',m.name_as_read,q);node('p',m.correction_text||'Patient was unsure.',q);}}if(d.fallback_reason)node('p',{unsupported_language:'This language is not yet verified for calls. Review the prescription manually.',medication_limit:'This prescription needs staff review because of its length.',consent_withdrawn:'The patient withdrew consent.'}[d.fallback_reason]||d.fallback_reason,body,'muted');
if(['review','fallback'].includes(d.status)){node('h3','Verify against the original prescription',body);node('p','Corrections are not applied automatically.',body,'muted');const form=node('form','',body),meds=node('div','',form);d.medications.forEach(m=>editor(meds,m));const add=node('button','+ Add medicine',form);add.type='button';add.onclick=()=>editor(meds);const reason=field(form,'Verification notes');const approve=node('button','Approve reviewed prescription',form,'primary');approve.style.marginTop='16px';form.onsubmit=async e=>{e.preventDefault();approve.disabled=true;try{await api('confirmations/'+d.call_id+'/approve','POST',{medications:readMeds(meds),reason:reason.value,version:d.version});$('detail').close();await load();say('Prescription approved. You can now schedule reminders.');}catch(err){say(err.message,true);}finally{approve.disabled=false;}};}
else{summarize(body,d.approved_medications||d.medications);if(d.status==='pending'){const preview=node('button','Preview confirmation call',body);preview.onclick=async()=>{try{const p=await api('confirmations/'+d.call_id+'/preview'),area=node('div','',body);node('h3','Call preview',area);node('pre',p.task||'Staff review required.',area);(p.live_blockers||[]).forEach(x=>node('p',x,area,'muted'));const call=node('button','Place one live call',area,'primary');call.disabled=p.live_blockers.length>0||d.dispatch_state!=='not_sent';call.onclick=async()=>{if(!confirm('Place one real call to '+d.phone_number+'? This may consume one call credit.'))return;call.disabled=true;try{await api('confirmations/'+d.call_id+'/dispatch','POST',{});$('detail').close();await load();say('Call submitted. Refresh to check for the outcome.');}catch(err){say(err.message,true);}};preview.disabled=true;}catch(err){say(err.message,true);}};}
if(['confirmed','scheduled'].includes(d.status)){const form=node('form','',body);node('h3','Schedule a reminder',form);const wrap=node('label','Medicine',form,'field'),select=node('select','',wrap);(d.approved_medications||d.medications).forEach(m=>select.add(new Option(m.name,m.name)));const due=field(form,'Reminder time · '+Intl.DateTimeFormat().resolvedOptions().timeZone);due.type='datetime-local';const save=node('button','Save reminder',form,'primary');save.style.marginTop='16px';form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('confirmations/'+d.call_id+'/schedule','POST',{due_at:[new Date(due.value).toISOString()],medication_names:[select.value],version:d.version});$('detail').close();await load();say('Reminder saved.');}catch(err){say(err.message,true);}finally{save.disabled=false;}};}}$('detail').showModal();}
function renderJobs(){const parent=$('jobs');parent.replaceChildren();if(!jobs.length){node('p','No reminders yet. Approve a prescription, then choose a medicine and reminder time.',parent,'muted');return;}jobs.forEach(j=>{const row=node('div','',parent,'row'),a=node('div','',row);node('h3',patients.find(p=>p.patient_id===j.patient_id)?.name||j.patient_id,a);node('p',j.medication?.name||'Reminder',a,'muted');node('p',new Date(j.due_at).toLocaleString(),row);node('span',names[j.status]||j.status,row,'pill');});}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>token?show(b.dataset.view):say('Unlock the workspace first.'));$('new').onclick=()=>show('intake');$('cancel').onclick=()=>show('queue');$('close').onclick=()=>$('detail').close();$('addmed').onclick=()=>editor($('medications'));$('search').oninput=render;$('filter').onchange=render;
$('loginform').onsubmit=async e=>{e.preventDefault();token=$('token').value.trim();try{await load();$('token').value='';$('login').hidden=true;$('workspace').hidden=false;$('refresh').hidden=false;$('lock').hidden=false;$('notice').hidden=true;}catch(err){token='';say(err.message,true);}};$('refresh').onclick=async()=>{try{await load();say('Workspace updated.');}catch(err){say(err.message,true);}};$('lock').onclick=()=>{token='';records=[];patients=[];jobs=[];$('workspace').hidden=true;$('login').hidden=false;$('refresh').hidden=true;$('lock').hidden=true;$('detail').close();$('detailbody').replaceChildren();$('records').replaceChildren();$('jobs').replaceChildren();$('intakeform').reset();$('existing').replaceChildren(new Option('Add a new patient',''));$('savedscans').replaceChildren(new Option('Choose a saved scan',''));$('medications').replaceChildren();editor($('medications'));$('notice').hidden=true;};
$('existing').onchange=()=>{const p=patients.find(p=>p.patient_id===$('existing').value);for(const[id,key]of [['name','name'],['phone','phone'],['language','language'],['region','region'],['evidence','consent_evidence']])$(id).value=p?.[key]||(['language','region'].includes(id)?(id==='language'?'en-IN':'IN'):'');$('consent').checked=Boolean(p?.consent&&!p?.consent_withdrawn_at);};
$('intakeform').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const meds=readMeds($('medications'));const id=$('existing').value||crypto.randomUUID(),original=patients.find(p=>p.patient_id===id)||{};await api('patients','PUT',{patient_id:id,name:$('name').value.trim(),phone:$('phone').value.trim(),language:$('language').value,region:$('region').value,consent:$('consent').checked,consent_evidence:$('evidence').value.trim(),caregiver_name:original.caregiver_name,caregiver_phone:original.caregiver_phone,caregiver_language:original.caregiver_language,caregiver_region:original.caregiver_region});await api('intakes','POST',{patient_id:id,source_id:$('source').value.trim(),medications:meds,ocr_reviewed:!!ocrScan&&$('ocrchecked').checked});$('intakeform').reset();$('medications').replaceChildren();editor($('medications'));await load();show('queue');say('Prescription saved. No call has been placed.');}catch(err){say(err.message,true);}finally{$('save').disabled=false;}};editor($('medications'));

let ocrScan=null,ocrDrafts=[],ocrGeneration=0;
function clearOCR(){ocrGeneration++;ocrScan=null;ocrDrafts=[];$('ocrtext').textContent='';$('ocrresult').hidden=true;$('ocrchecked').checked=false;$('ocrchecked').required=false;$('source').readOnly=false;}
$('ocrfile').onchange=()=>{clearOCR();};
$('intakeform').addEventListener('reset',clearOCR);
$('extractocr').onclick=async()=>{const f=$('ocrfile').files[0];if(!f){say('Choose a prescription file first.',true);return;}if(f.size>10*1024*1024){say('Maximum upload size is 10 MB.',true);return;}clearOCR();const requestGeneration=ocrGeneration,requestToken=token;$('extractocr').disabled=true;$('save').disabled=true;say('Reading the prescription locally…');try{const r=await fetch('/local/ocr/extract',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/octet-stream'},body:f});const d=await r.json();if(requestToken!==token||requestGeneration!==ocrGeneration)return;if(!r.ok)throw Error(d.detail||'OCR failed');displayScan(d);await loadScans();say('Scan saved. Use suggested fields, then verify against the original and fill missing details.');}catch(e){say(e.message,true);}finally{$('extractocr').disabled=false;$('save').disabled=false;}};

async function loadScans(){const scans=await api('ocr');$('savedscans').replaceChildren(new Option('Choose a saved scan',''));scans.forEach(d=>$('savedscans').add(new Option((d.created_at?new Date(d.created_at).toLocaleString():d.scan_id)+' · '+d.pages+' page(s)',d.scan_id)));}
function displayScan(d){ocrScan=d.scan_id;ocrDrafts=d.draft_medications||[];$('source').value=d.scan_id;$('source').readOnly=true;$('ocrtext').textContent=d.text;$('ocrresult').hidden=false;$('ocrchecked').checked=false;$('ocrchecked').required=true;$('usedraft').disabled=!ocrDrafts.length;}
$('openscan').onclick=async()=>{try{if(!$('savedscans').value)throw Error('Choose a saved scan first.');displayScan(await api('ocr/'+encodeURIComponent($('savedscans').value)));say('Saved scan loaded. Review the source before saving.');}catch(e){say(e.message,true);}};
$('usedraft').onclick=()=>{if(!ocrDrafts.length)return;if(!confirm('Replace the current medicine fields with unverified suggestions from this scan?'))return;$('medications').replaceChildren();ocrDrafts.forEach(m=>editor($('medications'),m));$('ocrchecked').checked=false;say('Suggestions loaded. Blank fields were not present in the source. Verify all values before saving.');};
$('downloadsource').onclick=async()=>{try{const r=await fetch('/local/ocr/'+encodeURIComponent(ocrScan)+'/source',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Original file is unavailable for this scan.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='prescription-source';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){say(e.message,true);}};
